# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AniDesu' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AniDesu
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Kingfisher', '~> 4.0'
pod 'Tabman', '~> 1.0'
pod 'Hero'
pod 'Cosmos', '~> 14.0'
pod 'Eureka'
pod 'WCLShineButton'
end
